name: test

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  test_linux:
    name: "test on linux"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          cache: "pip"
          cache-dependency-path: requirements_dev.txt
      - run: script/setup --dev
      - run: |
          test $(script/run --version) = $(cat wyoming_porcupine3/VERSION)
      - run: script/lint
      - run: script/test